/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:9eb9e404-72f8-495f-a760-1b20fb45c5ad",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_O0WYUBp27",
    "aws_user_pools_web_client_id": "1teprjfiagjkd0m4hslevuctfq",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://hyfppjcmhnekdbhugty7cdcsjm.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ikygy37qvjhhphetapy6jfsrr4",
    "aws_user_files_s3_bucket": "scanatsubscriber620f032716d7410c9e97e968f28666314831-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
