/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": process.env.GATSBY_USER_AUTH_POOL_ID,
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_R1vdv4w76",
    "aws_user_pools_web_client_id": process.env.GATSBY_USER_AUTH_WEBCLIENT_ID,
    "oauth": {}
};


export default awsmobile;
